name: wheels_app
description: A teen rides sharing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.20.0
  google_place: ^0.4.0
  #google_maps_place_picker_mb: ^3.1.2
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
dependency_overrides:
  http: ^1.1.0
flutter:
  uses-material-design: true