// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvA6KEuWIzrLcUgZP_jFNFmFSJ7ai0gs',
    appId: '1:826213863049:web:d0c04fcb40e32c15514058',
    messagingSenderId: '826213863049',
    projectId: 'wheels-new-app',
    authDomain: 'wheels-new-app.firebaseapp.com',
    storageBucket: 'wheels-new-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU0Mp8HWSiC0uJSDYTR1LjLrRB48l6P8',
    appId: '1:826213863049:android:b79b2c46817d57ca514058',
    messagingSenderId: '826213863049',
    projectId: 'wheels-new-app',
    storageBucket: 'wheels-new-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNPAOClIm2kXLMPfquK91jz_J80Y-vbc',
    appId: '1:826213863049:ios:b3ad0181f0ffe3b6514058',
    messagingSenderId: '826213863049',
    projectId: 'wheels-new-app',
    storageBucket: 'wheels-new-app.firebasestorage.app',
    iosBundleId: 'com.example.wheelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXNPAOClIm2kXLMPfquK91jz_J80Y-vbc',
    appId: '1:826213863049:ios:b3ad0181f0ffe3b6514058',
    messagingSenderId: '826213863049',
    projectId: 'wheels-new-app',
    storageBucket: 'wheels-new-app.firebasestorage.app',
    iosBundleId: 'com.example.wheelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgvA6KEuWIzrLcUgZP_jFNFmFSJ7ai0gs',
    appId: '1:826213863049:web:97cc34c329b36c76514058',
    messagingSenderId: '826213863049',
    projectId: 'wheels-new-app',
    authDomain: 'wheels-new-app.firebaseapp.com',
    storageBucket: 'wheels-new-app.firebasestorage.app',
  );

}