// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQsZRPmx0a-_TPwqSXhfPAnh8bHpSqP0o',
    appId: '1:544084308758:web:c03a9dab764beef6929637',
    messagingSenderId: '544084308758',
    projectId: 'wheels-app-updated',
    authDomain: 'wheels-app-updated.firebaseapp.com',
    storageBucket: 'wheels-app-updated.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAahODFrZU-VFFfsykyKez5W-K_5LEMQ-I',
    appId: '1:544084308758:android:8a5d2ae1a48e6130929637',
    messagingSenderId: '544084308758',
    projectId: 'wheels-app-updated',
    storageBucket: 'wheels-app-updated.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm6BaNHC8eDHALMcfXdu1pX1chFf10ws0',
    appId: '1:544084308758:ios:bcaa37da921cef61929637',
    messagingSenderId: '544084308758',
    projectId: 'wheels-app-updated',
    storageBucket: 'wheels-app-updated.firebasestorage.app',
    iosBundleId: 'com.example.wheelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm6BaNHC8eDHALMcfXdu1pX1chFf10ws0',
    appId: '1:544084308758:ios:bcaa37da921cef61929637',
    messagingSenderId: '544084308758',
    projectId: 'wheels-app-updated',
    storageBucket: 'wheels-app-updated.firebasestorage.app',
    iosBundleId: 'com.example.wheelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQsZRPmx0a-_TPwqSXhfPAnh8bHpSqP0o',
    appId: '1:544084308758:web:2da237642f1b42e3929637',
    messagingSenderId: '544084308758',
    projectId: 'wheels-app-updated',
    authDomain: 'wheels-app-updated.firebaseapp.com',
    storageBucket: 'wheels-app-updated.firebasestorage.app',
  );
}
